### ISSUE TITLE
Explorations

### ISSUE THREAD

**Issue by gtindo** [osscameroon/yotas#3]
Summary

We need to figure out how GitHub App and Oauth work, explore solutions for DB migration, ORM and Golang frameworks.

**Comment by Sanix-Darker** [comment]
For the explorations on github-app/webhook:
- i finished setting up a github application called ['yotas-webhook'](https://github.com/apps/yotas-webhook) and installed it on osscameroon, 
- then i created a [handler project](https://github.com/Sanix-Darker/yotas-webhook) watching PR events(ref: README).

Now i think we need to figure out how it will send those informations to the yotas api !
